// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelGalleryWeb.Repositories;

namespace TravelGalleryWeb.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20190205140115_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028");

            modelBuilder.Entity("TravelGalleryWeb.Models.Album", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Name");

                    b.ToTable("Albums");
                });

            modelBuilder.Entity("TravelGalleryWeb.Models.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AlbumName");

                    b.Property<string>("Comment");

                    b.Property<string>("FullPath");

                    b.Property<int>("Tag");

                    b.Property<int>("Year");

                    b.HasKey("Id");

                    b.HasIndex("AlbumName");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("TravelGalleryWeb.Models.Photo", b =>
                {
                    b.HasOne("TravelGalleryWeb.Models.Album", "Album")
                        .WithMany("Photos")
                        .HasForeignKey("AlbumName")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
